### ISSUE TITLE
mildom.LiveStream get error 'realtime_playback_info'

### ISSUE THREAD

**Issue by JC-Chung** [Alpaca131/mildom_lib#2]
It get error 'realtime_playback_info' at about 2022-02-17 21:59:05~21:59:07
Cause I use try-except so can't reproduce the error

def get_mildom_live(user_id):
    live_stream = mildom.LiveStream(user_id)
    return live_stream

```py
user_id = 10882672
live = get_mildom_live(user_id) # I seems that the error is from this.
if live.is_live:
    print(f"{live.author_name} start live {live.title}") # Cause this didn't show when 21:59:07
```

https://github.com/Alpaca131/mildom_lib/blob/3841e93743f14437f0464303c45af72653bec47e/mildom/__init__.py#L105

```
... other things spent about 3 seconds
kson組長(けいそん) didn't live now.
2022-02-17 21:58:54.219798 Total 4.621 seconds (wait 9 seconds)

... other things spent about 3 seconds
'realtime_playback_info'                                         << The error
2022-02-17 21:59:07.929586 Total 4.697 seconds (wait 9 seconds)

... other things spent about 3 seconds
kson組長(けいそん) start live ICARUSの世界で生き残れ！！【kson組長】 << started_since: 2022-02-17 21:59:04
Successfully posted in Discord, code 204.
2022-02-17 21:59:22.111924 Total 5.17 seconds (wait 9 seconds)
```

**Comment by Alpaca131** [comment]
Thank you for reporting.  Investigating.

**Comment by Alpaca131** [comment]
What is the Time Zone of that time?

**Comment by Alpaca131** [comment]
I think Mildom was not ready for live stream at that time, so "realtime_playback_on" was 1 (it means the real time playback is enabled) but there was no detailed info about playback ("realtime_playback_info" was not in the response.).

**Comment by JC-Chung** [comment]
> What is the Time Zone of that time?

UTC+8

**Comment by Alpaca131** [comment]
Fixed this by latest commit.

**Comment by JC-Chung** [comment]
> Fixed this by latest commit.

Thanks.

**Comment by Alpaca131** [comment]
Updated PyPI package.
https://pypi.org/project/mildom/1.4.3/
Please update your local library using pip command.
`pip install -U mildom`
