### ISSUE TITLE
Member only stream will lost body in mildom.LiveStream

### ISSUE THREAD

**Issue by JC-Chung** [Alpaca131/mildom_lib#3]
Or only can use `mildom.User(user_id)` when live member only stream?
user_id = 10882672

```
Traceback (most recent call last):
  File "C:\Users\test01\Desktop\Twitter\new_twitcas.py", line 418, in <module>
    main()
  File "C:\Users\test01\Desktop\Twitter\new_twitcas.py", line 294, in main
    live = get_mildom_live(MILDOM_USERNAME[i]["Id"])
  File "C:\Users\test01\Desktop\Twitter\new_twitcas.py", line 98, in get_mildom_live
    live_stream_ = mildom.LiveStream(user_id)
  File "C:\Users\test01\AppData\Local\Programs\Python\Python39\lib\site-packages\mildom\__init__.py", line 87, in __init__
    response = api_request.live_info_request(user_id)["body"]
KeyError: 'body'
```

**Comment by Alpaca131** [comment]
Nope. I tried but it succeeded.
Maybe something is wrong with your network, or exceeded the rate limit.
To figure out the rate limit of Mildom API, could you tell me the duration that you're running that code?

**Comment by Alpaca131** [comment]
Actually, I'm not the developer of Mildom, so I don't know well about rate limit and other restrictions.

**Comment by Alpaca131** [comment]
If you can reproduce the error again, could you tell me the response of the API?
You can get it by
```python
import mildom

print(mildom.api_request.profile_v2_request(10882672))
```

**Comment by JC-Chung** [comment]
> Nope. I tried but it succeeded. Maybe something is wrong with your network, or exceeded the rate limit. To figure out the rate limit of Mildom API, could you tell me the duration that you're running that code?

about every 14 seconds 1 round, and before stream start, the code still working over many days.
Even get thumbnail,title and description update before start stream.

**Comment by JC-Chung** [comment]
> If you can reproduce the error again, could you tell me the response of the API? You can get it by
> 
> ```python
> import mildom
> 
> print(mildom.api_request.profile_v2_request(10882672))
> ```

Your code success.

This is mine.
```
import mildom

def get_mildom_live(user_id): # l
    live_stream_ = mildom.LiveStream(user_id)
    return live_stream_

live = get_mildom_live(10882672)
```
```

Traceback (most recent call last):
  File "C:\Users\test01\Desktop\Twitter\xx.py", line 7, in <module>
    live = get_mildom_live(10882672)
  File "C:\Users\test01\Desktop\Twitter\xx.py", line 4, in get_mildom_live
    live_stream_ = mildom.LiveStream(user_id)
  File "C:\Users\test01\AppData\Local\Programs\Python\Python39\lib\site-packages\mildom\__init__.py", line 87, in __init__
    response = api_request.live_info_request(user_id)["body"]
KeyError: 'body'
```

**Comment by JC-Chung** [comment]
Maybe problem is on my description.

In member only stream
`mildom.LiveStream(user_id)` will get `KeyError: 'body'` (Issue title)
`mildom.user(user_id)` success and can get some info about live stream.
So I ask
> Or only can use mildom.User(user_id) when live member only stream?

in Issue comment.

**Comment by JC-Chung** [comment]
```py
import mildom
import json

print(mildom.api_request.live_info_request(10882672))
```
```py
{'code': 1001, 'message': 'この配信はサブスクライバー限定配信です。アプリを最新バージョンにアップデートしてください。', 'setting_version': 2030, 'ts_ms': 1645445875781}
```

**Comment by JC-Chung** [comment]
Now need add `mark=1` to get live info. (Or this is a special case cause it is member only stream ?

https://github.com/Alpaca131/mildom_lib/blob/d854c5904ea1d641dfd7a1d89182ddfeea9018d3/mildom/api_request.py#L26

```
https://cloudac.mildom.com/nonolive/gappserv/live/enterstudio?__platform=web&user_id=10882672&mark=1
```

**Comment by Alpaca131** [comment]
Sorry, I missed the title,,,

**Comment by Alpaca131** [comment]
Thanks. It seems the problem happens only on LiveStream api request.
I'll try that solution when I found another member-only live stream.

If I could confirm that works, I'll merge this PR(#4 ) and release a new version.

**Comment by JC-Chung** [comment]
@Alpaca131 11050449 Need add `mark=1`, too
from `Search 限定`

**Comment by Alpaca131** [comment]
Thank you! I confirmed it works.
